"""THE FILM SCENE — the world, the car in it, and the camera that shoots them.

    /opt/blender-5.2.0-linux-x64/blender -b \
        render/world/assembly/r2/assembly7.blend --factory-startup \
        -P tools/build_film_scene.py -- --out render/film11.blend

WHY THIS EXISTS
---------------
Until now the world and the car have never been in the same file. The world
assemblies render with the ONER camera and NO CAR — that is what
`render/world/assembly/r2/v121/*.png` are — and `world/car_anim.blend` has the
car and the showroom and no circuit. Every statement about how the car looks on
the road has therefore been a statement about a number.

This appends the `CAR` collection — 616 meshes, `CAR_ROOT` and the eight
`CARRIG_*` hub empties, with all their animation — into a world blend, and builds
the camera rig on top with the film's own grade.

APPENDED, NOT LINKED, AND THAT IS NOT A STYLE CHOICE
-----------------------------------------------------
A linked library is a second file, and `~/vast-render` ships exactly one blend to
the GPU. A linked car would render as an empty hole on the farm and as a car
here, which is the worst possible failure: it looks right on the machine where
nobody is watching the render.

WHICH WORLD
-----------
Whatever blend this is run against — but `render/world/assembly/r2/SHIPPING.md`
is unambiguous that `assembly5.blend` MUST NOT BE RENDERED FROM (its
`BR_Transit_NorthWall` stands up to 3.333 m outboard of the declared corridor,
in the shot the camera flies at 200 km/h), so this refuses to run on it by name.

`assembly7.blend` is the ship as of 2026-08-03. It is `assembly6` with nine
`DR_*` dressing materials repaired and NOTHING else: 0 of 28,781 objects differ
by vertex fingerprint, and the repair was regenerated by re-running
`world/build_dressing.py` rather than patched into a built blend. `assembly6` is
not dangerous, only stale, so it is NOT refused — it is the control this build
was measured against, and building on it deliberately is how the world's
contribution to a frame is separated from the film scene's.
"""

import argparse
import importlib.util
import json
import os
import sys
import time

import bpy

R2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(R2, "anim"))
sys.path.insert(0, os.path.join(R2, "world"))
sys.path.insert(0, os.path.join(R2, "tools"))   # shipping_world, gate_exit


SHIPPING_MD = os.path.join(
    R2, "render/world/assembly/r2/SHIPPING.md")


def declared_shipping_world(path=SHIPPING_MD):
    """The name of the ship, READ FROM THE ONE PLACE THAT DECLARES IT.

    THIS FILE USED TO HAVE NO OPINION ABOUT ITS OWN WORLD AT ALL. The world is
    whatever blend Blender was launched on -- `bpy.data.filepath` -- so the
    build silently accepted any assembly handed to it and said nothing. That is
    not a hardcoded-path defect, it is the more dangerous one: there was no
    value to go stale because there was no value.

    MEASURED, 2026-08-03: `assembly7.blend` was built at 04:45 with the nine
    `DR_*` dressing materials repaired. `film9.blend` was built at 11:39 and
    `film10.blend` at 17:15 -- both AFTER the fixed world existed, both on
    `assembly6`, and neither said a word about it. A third agent found it by
    inspecting the finished blends, which is the only reason anyone knows.

    So the declaration lives in `SHIPPING.md`, which is the file that actually
    decides, and this reads it rather than keeping a second copy that could
    disagree. If it cannot parse a declaration it RAISES -- an unreadable
    declaration must not degrade into "anything goes", which is the state this
    replaces.

    THE PARSER MOVED OUT (2026-08-03, R2-100). It was inline here, and
    `tools/input_stamp.py` -- which stamps WHICH world every screen-presence
    number was measured against -- carried a hardcoded `assembly6.blend`
    instead. One declaration deserves one reader: two parsers of the same file
    is a smaller version of the same defect, and the plain-python caller could
    not import this module at all because this one imports `bpy`. Both now go
    through `tools/shipping_world.py`, which is stdlib-only and has its own
    controls (`--selftest`). Behaviour here is unchanged except that a
    SHIPPING.md with no declaration HEADING now raises too, instead of
    searching the whole file for a bold assembly name.
    """
    import shipping_world
    return shipping_world.declared_shipping_world(path)


def refuse_unless_world_is_declared(src, override):
    """RAISE unless this build is on the declared ship, or says why not.

    An override is legitimate -- `film10.blend` was deliberately built on
    `assembly6` as the one-variable control that isolated the relight from the
    world -- but it has to be STATED. A control and a stale build look identical
    on disk; the only difference is that somebody meant one of them.
    """
    got = os.path.basename(src)
    ship = declared_shipping_world()
    if got == ship:
        print(">> WORLD: %s, the ship declared in SHIPPING.md" % got)
        return ship
    if not override:
        raise SystemExit(
            "REFUSING: this is %s and SHIPPING.md declares %s. Two film scenes "
            "have already shipped on a superseded world without anyone "
            "noticing, because nothing checked. If this is deliberate -- a "
            "control, an A/B -- pass --world-override with the reason."
            % (got, ship))
    print(">> WORLD: %s, NOT the declared ship (%s). Override reason: %s"
          % (got, ship, override))
    return ship


def report_world_staleness(src):
    """Say whether the assembly is older than the modules that generate it.

    The check above asks "is this the RIGHT assembly". It cannot ask "is this
    assembly still what its own source would produce", and those are different
    questions with the same failure mode -- a value nobody re-derived.

    MEASURED while writing this: `assembly7.blend` was built 2026-08-03 04:45
    and `world/build_dressing.py` was modified at 18:36 the same day (R2-072,
    by-name socket setters dropping writes silently). So the declared ship was
    already stale against its own generator within the day.

    R2-1822: THIS NOW REFUSES. It used to warn, for a reason worth preserving:
    "a refusal here would block every film build for as long as any world module
    is being worked on, which on this project is always, and a guard that must be
    routinely overridden teaches people to override guards." That argument is
    correct about MTIME staleness and it is why this check stayed a warning --
    but the warning was then printed on every film build and read as noise, and
    `film18_breach.blend` shipped without FOUR landed world changes while every
    other gate passed. A warning nobody can act on is not weaker than a refusal;
    it is a refusal that has been pre-overridden for everyone, permanently.

    What makes refusing affordable is that the check is now about CONTENT, not
    timestamps. `assemble.py` records the sha256 of every generator module it
    read, at read time, in `<blend>_build.json` and in the scene itself. So:

      * re-saving a module without changing it does not fire -- the hash is
        equal, and mtime staleness of that kind was most of the false alarms
      * a module edited DURING the assembly build DOES fire, which mtime cannot
        see at all: assembly11 read build_terrain.py at 22:06, the file changed
        at 22:25, the blend saved at 22:40, and save-time > module-mtime reported
        FRESH on a world built from a source state that no longer existed
      * the answer travels with the artefact, so it is still true if the sidecar
        is lost or the blend is moved

    Assemblies built before R2-1822 carry no fingerprint. For those this falls
    back to the old mtime comparison and STILL refuses, because the alternative
    is the film18 outcome; the message says which check spoke, since the mtime
    arm has false positives the hash arm does not.

    `--world-override REASON` overrides deliberately, and the reason is printed
    into the build log.
    """
    fresh, why = _world_source_state(src)
    if fresh:
        print(">> WORLD STALENESS: none — %s" % why)
        return []
    print(">> WORLD STALENESS: %s" % why)
    return [why]


def _world_source_state(src):
    """(is_fresh, human_reason). Hash arm when available, mtime arm otherwise."""
    import hashlib
    recorded = None
    sidecar = src.replace(".blend", "_build.json")
    if os.path.exists(sidecar):
        try:
            with open(sidecar) as fh:
                recorded = json.load(fh).get("source_sha256")
        except Exception:
            recorded = None

    wdir = os.path.join(R2, "world")
    if recorded:
        differ = []
        for rel, want in sorted(recorded.items()):
            p = os.path.join(R2, rel)
            try:
                with open(p, "rb") as fh:
                    got = hashlib.sha256(fh.read()).hexdigest()
            except OSError:
                got = None
            if got != want:
                differ.append(rel)
        if differ:
            return False, ("%s was built from a DIFFERENT source state. %d "
                           "module(s) differ by content: %s. A rebuilt assembly "
                           "would not be this file."
                           % (os.path.basename(src), len(differ),
                              ", ".join(differ[:6])))
        return True, ("%s matches its recorded source fingerprint over %d "
                      "module(s) [content check]" % (os.path.basename(src),
                                                     len(recorded)))

    try:
        w_mtime = os.path.getmtime(src)
    except OSError:
        return True, "no assembly to check"
    newer = []
    for fn in sorted(os.listdir(wdir)):
        if not (fn.startswith("build_") and fn.endswith(".py")):
            continue
        m = os.path.getmtime(os.path.join(wdir, fn))
        if m > w_mtime:
            newer.append((fn, (m - w_mtime) / 3600.0))
    if newer:
        return False, ("%s predates %d of its own generator module(s) "
                       "[mtime check -- this assembly predates R2-1822 and "
                       "carries no source fingerprint]: %s"
                       % (os.path.basename(src), len(newer),
                          ", ".join("world/%s +%.1fh" % (f, d) for f, d in newer[:6])))
    return True, ("%s is newer than every world/build_*.py [mtime check -- no "
                  "source fingerprint recorded]" % os.path.basename(src))


def refuse_unless_levelled(scene):
    """The last thing before ANY save. Never inside a branch.

    THIS GUARD ALREADY FAILED ONCE, BY BEING CONDITIONAL. It was written to make
    an un-levelled set a build-time refusal, and it was placed inside
    `if not a.no_rig:` -- so a build that skipped the rig skipped the guard.
    `film9.blend` shipped with the round-1 practicals untouched at 3,737 W
    against the levelled 46,203 W, and nobody found out until ten rendered
    frames were measured: beats 1-2 came back at mean 0.05-0.11 with up to
    3.35 % of the frame at literal 0/0/0, against a target of mean 0.32-0.48
    and 0.0000 %.

    A guard inside a conditional is not a guard -- it is a guard *and* a bet
    that the conditional is true. There are three `save_as_mainfile` calls in
    this file and this must precede every one of them, so the only way to ship
    an un-levelled film scene is to delete this function.

    It imports its own dependency rather than closing over a name bound in some
    branch, for the same reason.
    """
    import showroom_lighting as SL
    SL.assert_levelled(scene)


def parse_args():
    argv = sys.argv
    argv = argv[argv.index("--") + 1:] if "--" in argv else []
    p = argparse.ArgumentParser()
    p.add_argument("--car", default=os.path.join(R2, "world/car_anim.blend"))
    p.add_argument("--sheet", default=os.path.join(R2, "docs/beat_sheet.json"))
    p.add_argument("--telemetry",
                   default=os.path.join(R2, "telemetry/telemetry.csv"))
    p.add_argument("--spec", default=os.path.join(R2, "docs/circuit_spec.json"))
    p.add_argument("--out", required=True)
    p.add_argument("--world-override", metavar="REASON", default=None,
                   help="build on a world SHIPPING.md does not declare, and "
                        "say why. Two film scenes shipped on a superseded "
                        "world because nothing asked this question.")
    p.add_argument("--no-rig", action="store_true",
                   help="append the car only; leave the world's own camera")
    p.add_argument("--keep-r1-glass", action="store_true",
                   help="keep round 1's ten GW_Right_Glass_* placeholder panes. "
                        "sim/out/apply_requirements.json R3 requires them GONE; "
                        "this exists only for an A/B of the 33.5 mm move.")
    p.add_argument("--no-showroom", action="store_true",
                   help="append the CAR collection only. Beats 1, 2 and 3 — "
                        "1,056 frames, 35 %% of the film — then have no set.")
    return p.parse_args(argv)


def main():
    t_start = time.time()          # R2-502: the freshness datum for the token
    a = parse_args()
    src = bpy.data.filepath
    if os.path.basename(src) == "assembly5.blend":
        raise SystemExit(
            "REFUSING: assembly5.blend is superseded and must not be rendered "
            "from — see render/world/assembly/r2/SHIPPING.md. Use assembly7.")
    # ...and assembly5 stays a hard refusal that NO override reaches, because
    # its BR_Transit_NorthWall is 3.333 m into the corridor the camera flies at
    # 200 km/h. The check below is the softer one: the right world, or a stated
    # reason for a different one.
    refuse_unless_world_is_declared(src, a.world_override)
    stale = report_world_staleness(src)
    if stale:
        if a.world_override:
            print(">> WORLD STALENESS OVERRIDDEN deliberately: %s" % a.world_override)
        else:
            raise SystemExit(
                "REFUSING: the world this film would be built on is not what its "
                "own source would produce, so landed changes would be absent from "
                "every frame while every other gate passed -- which is exactly "
                "what happened to film18 (R2-1701). Rebuild the assembly with\n"
                "    render/world/assembly/r2/v126/build_assembly12.sh\n"
                "or, if this is deliberate (a control, an A/B, a historical "
                "re-measurement), pass --world-override with the reason.")

    scene = bpy.context.scene
    sheet = json.load(open(a.sheet))
    total = int(sheet["total_frames"])
    scene.frame_start = 1
    scene.frame_end = total
    scene.render.fps = 24

    before_objs = set(o.name for o in bpy.data.objects)

    # ---- the car ---------------------------------------------------------
    t0 = time.time()
    loaded = []
    with bpy.data.libraries.load(a.car, link=False) as (src_data, dst_data):
        if "CAR" not in src_data.collections:
            raise SystemExit("%s has no CAR collection" % a.car)
        dst_data.collections = ["CAR"]
        loaded = dst_data.collections
    # `dst_data.collections` is rewritten in place with the real datablocks on
    # exit from the context manager, so this is the collection that was just
    # appended and not a name lookup that could find the world's own.
    car = [c for c in loaded if c is not None][0]
    scene.collection.children.link(car)
    print(">> appended CAR (%d objects) from %s in %.1f s"
          % (len(car.objects), a.car, time.time() - t0))

    root = None
    for o in car.objects:
        if o.name.startswith("CAR_ROOT"):
            root = o
    if root is None:
        raise SystemExit("the appended CAR collection has no CAR_ROOT")
    hubs = [o.name for o in car.objects if o.name.startswith("CARRIG_")]
    if len(hubs) != 8:
        raise SystemExit("the appended CAR collection carries %d CARRIG_* hub "
                         "empties, expected 8: %s" % (len(hubs), hubs))
    orphans = [o.name for o in car.objects
               if o.parent is not None and o.parent.name not in
               set(x.name for x in car.objects)]
    if orphans:
        raise SystemExit("%d appended parts have a parent outside the CAR "
                         "collection: %s" % (len(orphans), orphans[:6]))
    if not (root.animation_data and root.animation_data.action):
        raise SystemExit("the appended CAR_ROOT carries NO animation — the car "
                         "would sit on the dais for the whole film. Build "
                         "world/car_anim.blend with anim/build_car_anim.py.")
    print(">> CAR_ROOT %r animated, %d children, %d hub empties"
          % (root.name, len(root.children), len(hubs)))

    # ---- the showroom ----------------------------------------------------
    # THE SET FOR 1,056 OF THE FILM'S 2,978 FRAMES, AND IT WAS BEING LEFT OUT.
    #
    # Beats 1 (assembly), 2 (launch) and 3 (breach) all happen INSIDE the
    # showroom, and the shipping world does not contain one: assembly6.blend's
    # object prefixes are VEG/DR/BR/SURF/ARCH/TER and the only showroom-ish
    # object in it is `ARCH_ShowroomSurrounds`. No floor, no dais, no glass.
    # MEASURED, first run of this file, 2026-08-03: with only `CAR` appended the
    # car's tyres sit +0.4400 m above `ARCH_Paving_Forecourt` for every one of
    # beat 1's frames -- the dais deck top (0.340) over the exterior paving
    # (-0.100) -- with nothing between them.
    #
    # It does not need a third file. `world/car_anim.blend` ALREADY carries the
    # set, in its own collections, because build_car_anim.py was run on the
    # showroom blend:
    #
    #     CAR       625   the car, CAR_ROOT, the 8 CARRIG_* hubs
    #     SHOWROOM   76   Floor, GW_* curtain wall, Turntable_Deck, Platform_Dais
    #     PROPS     189   including all 28 Vitrine_*, ALREADY UNPARENTED
    #     LIGHTS     61   the showroom's interior rig
    #     CAMERAS     4   dropped by the rig anyway, so not appended
    #
    # Appending from THIS file rather than from `world/verify_showroom.blend` is
    # the point: car_anim.blend is the post-unparent artefact. Its Vitrines are
    # in PROPS with parent None (MEASURED: 0 of 28 parented to CAR_ROOT), so the
    # display case full of brake discs stays bolted to the showroom floor instead
    # of flying round the circuit at 330 km/h. Appending the set from a second
    # file would also give the scene two copies of every vitrine.
    #
    # The transform is identity and the datum is exact, so this is a plain
    # append with no fitting: MEASURED on car_anim.blend, GW_Right_Glass_00 lies
    # in the plane x = 15.0000 == `world_contract.ACCESS_GLASS_X`, the breach
    # plane build_architecture calls a butt joint with no allowance, and
    # Turntable_Deck's top is z = 0.3400 == the spec's deck_top_z. Both are
    # re-asserted below rather than trusted.
    SET_COLLECTIONS = ("SHOWROOM", "PROPS", "LIGHTS")
    if a.no_showroom:
        print(">> --no-showroom: beats 1-3 (frames 1-1056) will have NO SET")
    else:
        t1 = time.time()
        with bpy.data.libraries.load(a.car, link=False) as (src_data, dst_data):
            missing = [c for c in SET_COLLECTIONS if c not in src_data.collections]
            if missing:
                raise SystemExit(
                    "%s has no %s collection(s). The showroom is the set for "
                    "beats 1-3; rebuild it with anim/build_car_anim.py."
                    % (a.car, missing))
            dst_data.collections = list(SET_COLLECTIONS)
            got_set = dst_data.collections
        for col in got_set:
            scene.collection.children.link(col)
            print(">> appended %s (%d objects)" % (col.name, len(col.objects)))

        # THE VITRINES. 28 of them, and 16 were parented to CAR_ROOT before
        # build_car_anim.py unparented them. If that ever regresses, this build
        # is where it must stop.
        vit = [o for o in bpy.data.objects if o.name.startswith("Vitrine_")]
        flying = [o.name for o in vit if o.parent is root]
        if flying:
            raise SystemExit(
                "REFUSING: %d Vitrine_* display cases are parented to CAR_ROOT "
                "and would be flown round the circuit at 330 km/h: %s"
                % (len(flying), flying[:6]))
        print(">> %d Vitrine_* appended, 0 parented to CAR_ROOT" % len(vit))

        # ---- THE SHOWROOM CEILING  (R2-508 / R2-517) --------------------- #
        #
        # WHY IT IS AN APPEND AND NOT A POST-BUILD TOOL.  R2-504 established the
        # ceiling cannot come from the assembly: the showroom enters the film
        # HERE, downstream of it, as an append at identity, and `assembly*.blend`
        # has no showroom in it at all.  The obvious consequence was a tool that
        # opens the finished 7.9 GB film, edits it and saves it -- and that shape
        # is wrong twice over.  It pages for an hour on an 11 GB box, and it
        # cannot be moved to the farm either: `rq exec` will not take a scene out
        # of the worker's cache, so the film would travel as an `--include`, and
        # `execremote.push_bundle` hardcodes `zstd -19 -T4` with no level
        # selection -- the pathology the *scene* path was already fixed for after
        # -19 was measured feeding a 4-5 MB/s wire at 1.3 MB/s.
        #
        # A library collection is 6.99 MB against the 7.9 GB the round trip
        # existed to move -- about 1,140x smaller -- and it joins a mechanism
        # this function already runs three times.  Same reasoning as the round-1
        # set: ship the definition, not the artefact.
        #
        # NOT RE-VERIFIED HERE, because the library refuses to write itself if it
        # carries a light datablock, a FILE image, an emissive material, a flat
        # material, or anything above the slab.  Round-tripped rather than
        # assumed: 21 objects / 73,996 polys, spanning z 5.5705-6.1980 under the
        # 6.200 soffit, with 46,203.313 W / 23 lamps / mark 3.628 /
        # assert_levelled PASS unchanged after the append.  `refuse_unless_levelled`
        # below is what actually holds that, and it runs after this.
        CEIL_BLEND = os.path.join(R2, "world/showroom_ceiling.blend")
        CEIL_COLL = "R2_SHOWROOM_CEILING"
        if not os.path.exists(CEIL_BLEND):
            raise SystemExit(
                "REFUSING: %s is missing. The showroom has had no ceiling since "
                "round 1 -- one cuboid with a 686 m2 top face -- and beat 1 now "
                "opens 18 mm at 10.00 deg of depression, which puts it IN FRAME "
                "1 (R2-508). Build it or pass --no-showroom." % CEIL_BLEND)
        with bpy.data.libraries.load(CEIL_BLEND, link=False) as (src_c, dst_c):
            if CEIL_COLL not in src_c.collections:
                raise SystemExit(
                    "REFUSING: %s has no %s collection; got %s"
                    % (CEIL_BLEND, CEIL_COLL, list(src_c.collections)[:8]))
            dst_c.collections = [CEIL_COLL]
        ceil = dst_c.collections[0]
        scene.collection.children.link(ceil)
        # MEASURED off the appended meshes, not quoted from the library's own
        # report. R2-517: that library's `build()` printed a `z_extent` taken
        # from its constants and was wrong by 190 mm, because the lowest thing up
        # there is a track-head barrel and not a beam. A number read back from
        # the datablocks cannot disagree with the datablocks.
        cz = [(o.matrix_world @ v.co).z
              for o in ceil.all_objects if o.type == "MESH"
              for v in o.data.vertices]
        npoly = sum(len(o.data.polygons) for o in ceil.all_objects
                    if o.type == "MESH")
        print(">> appended %s (%d objects, %d polys), z %.4f..%.4f MEASURED"
              % (ceil.name, len(ceil.all_objects), npoly, min(cz), max(cz)))
        if max(cz) > 6.2005:
            raise SystemExit(
                "REFUSING: the ceiling library reaches z %.4f, above the "
                "showroom soffit at 6.200. Its underside is the interior "
                "ceiling and is visible in beat 5." % max(cz))
        if any(o.type == "LIGHT" for o in ceil.all_objects):
            raise SystemExit(
                "REFUSING: the ceiling library carries a LIGHT datablock. The "
                "interior load is 46,203.313 W over 23 lamps and is asserted "
                "by refuse_unless_levelled below; a 24th lamp breaks it.")

        # THE BREACH PLANE. world_contract.ACCESS_GLASS_X, asserted in the
        # scene's own coordinates after the append.
        import world_contract as WC
        bpy.context.view_layer.update()
        glass = bpy.data.objects.get("GW_Right_Glass_00")
        if glass is None or glass.type != "MESH":
            raise SystemExit("no GW_Right_Glass_00 mesh after appending SHOWROOM")
        xs = [(glass.matrix_world @ v.co).x for v in glass.data.vertices]
        want_x = float(getattr(WC, "ACCESS_GLASS_X", 15.0))
        if max(abs(x - want_x) for x in xs) > 1e-3:
            raise SystemExit(
                "REFUSING: GW_Right_Glass_00 spans x %.4f..%.4f, not the "
                "declared breach plane ACCESS_GLASS_X = %.4f. The car breaches "
                "the glass at a station the whole film is timed against."
                % (min(xs), max(xs), want_x))
        deck = bpy.data.objects.get("Turntable_Deck")
        top = max((deck.matrix_world @ v.co).z for v in deck.data.vertices)
        if abs(top - 0.340) > 1e-3:
            raise SystemExit(
                "REFUSING: Turntable_Deck top is z = %.4f, not the 0.340 the "
                "car's contact solve stands it on." % top)
        floor = bpy.data.objects.get("Floor")
        ftop = max((floor.matrix_world @ v.co).z for v in floor.data.vertices)
        if abs(ftop) > 1e-3:                       # sim/out R4
            raise SystemExit(
                "REFUSING: showroom Floor top is z = %.4f, not 0.000. The "
                "breach sim baked 3,796 shard resting transforms against that "
                "plane; a floor 20 mm low leaves every one of them hovering."
                % ftop)
        if abs(scene.unit_settings.scale_length - 1.0) > 1e-9:   # sim/out R2
            raise SystemExit("REFUSING: scene unit scale_length is %r, not 1.0"
                             % scene.unit_settings.scale_length)
        print(">> SET DATUMS: breach plane x = %.4f (ACCESS_GLASS_X %.4f), "
              "Turntable_Deck top z = %.4f, Floor top z = %.4f, "
              "appended in %.1f s"
              % (xs[0], want_x, top, ftop, time.time() - t1))

        # ---- THE PRACTICALS, LEVELLED TO THE FILM'S EXPOSURE -------------
        # The showroom's interior rig is ROUND 1'S, carried forward untouched:
        # opus5-car-render/build/s05_lighting_v2.py -> f1_showroom.blend ->
        # beat1_anim.blend -> car_anim.blend, from which the LIGHTS collection
        # is appended whole above. Nothing in f1-round2 authors it.
        #
        # That rig was tuned on a transfer curve its own docstring pins to
        # "AgX + Medium High Contrast, EXPOSURE 0". This film grades at -3.628.
        # Without this call the set renders 3.628 stops under the level it was
        # lit for, and beat 1 loses 1.30 % of the frame to literal 0/0/0 -- a
        # continuous band along the car's floor edge and sidepod undercut, the
        # defining line on an F1 car. Erased, not merely dark.
        #
        # The lift is an IDENTITY, not a taste number: LIFT = -FILM_EXPOSURE, so
        # practicals x 2**3.628 viewed at -3.628 reproduce pixel-for-pixel what
        # they produced at 0.000 -- which is why every argument in s05_lighting_v2
        # (clip thresholds, radiance-vs-watts, source widening) survives intact.
        # Daylight through the glass is the one term that does NOT move, and that
        # is the entire point.
        #
        # Idempotent: it records `_sl_base` per datablock and always writes
        # base * 2**stops, so applying twice equals applying once.
        import showroom_lighting as SL
        SL.apply(scene)

        # ---- R3: ROUND 1'S EAST GLASS COMES OUT -------------------------
        # `sim/out/apply_requirements.json` R3, measured by the breach agent and
        # not negotiable: the ten `GW_Right_Glass_00..09` are round 1's
        # placeholder east wall -- four verts each, zero-thickness planes lying
        # exactly on x = 15.000 -- and `sim/apply_breach.py` replaces them with
        # real 11.5 mm laminate at x 14.95500..14.96650. Leaving them in puts two
        # east walls 33.5 mm apart: they z-fight through the 33 s of beat 1 that
        # is spent on this glass's reflections, and after the breach the deleted
        # wall's ghost pane is still standing in the aperture.
        #
        # They are deleted AFTER the datum assertion above and not before, so the
        # incoming x = 15.000 is still proved on the way past. The contract's
        # `ACCESS_GLASS_X` is unchanged by this: what moves 33.5 mm inboard is
        # the laminate's outer FACE, not the declared plane.
        if not a.keep_r1_glass:
            req = os.path.join(R2, "sim/out/apply_requirements.json")
            names = ["GW_Right_Glass_%02d" % i for i in range(10)]
            if os.path.exists(req):
                names = json.load(open(req)).get("delete_from_target", names)
            gone = []
            for n in names:
                ob = bpy.data.objects.get(n)
                if ob is not None:
                    bpy.data.objects.remove(ob, do_unlink=True)
                    gone.append(n)
            left = [n for n in names if bpy.data.objects.get(n) is not None]
            if left:
                raise SystemExit("failed to delete round 1 east glass: %s" % left)
            stray = [o.name for o in bpy.data.objects
                     if o.name.startswith("GW_Right_Glass")]
            if stray:
                raise SystemExit(
                    "GW_Right_Glass objects survive the R3 deletion: %s. The "
                    "breach sim would leave a ghost pane in the aperture."
                    % stray)
            front = len([o for o in bpy.data.objects
                         if o.name.startswith("GW_Front_")])
            print(">> R3: deleted %d round-1 east panes %s; %d GW_Front_* (the "
                  "SOUTH wall, y = -11.000) kept, as the contract requires"
                  % (len(gone), gone[:3] + ["..."] if len(gone) > 3 else gone,
                     front))
        else:
            print(">> --keep-r1-glass: the round-1 east wall STAYS. "
                  "sim/apply_breach.py will z-fight against it.")

    # ---- the grade, BEFORE the rig (the rig keys a delta from it) ---------
    import film_exposure as FX
    got = FX.apply(scene)
    print(">> GRADE from world/film_exposure.py: exposure %+.3f, view_transform "
          "%s, look %s" % (got["exposure"], got["view_transform"], got["look"]))

    # ---- the camera ------------------------------------------------------
    #
    # `build_camera_rig.main()` finishes through `fix_audit_blend.save_clean`,
    # which installs `R2_ProceduralSky` as the scene world. That is right for the
    # showroom blend it was written for and WRONG here: this world's light was
    # built by `world/build_sky.py`, and `world/film_exposure.py`'s -3.628 was
    # MEASURED under it — 39.0106 W/m2 including the atmosphere slab. Swapping
    # the world would relight the film and leave the exposure calibrated to a
    # sky that is no longer in the scene.
    #
    # So the world datablock is captured and restored, and the swap is asserted
    # rather than hoped about.
    #
    # ...EXCEPT THAT `assembly6.blend` HAS NO WORLD AT ALL, AND THE PARAGRAPH
    # ABOVE WAS WRONG ABOUT THAT.  MEASURED on the shipping assembly, 2026-08-03:
    # `bpy.context.scene.world is None`.  `render/world/assembly/r2/assemble.py`
    # builds `surface,barriers,architecture,terrain,dressing` and NOT `sky` — the
    # light is added later, by `render_setup3.py`, which calls
    # `build_sky.build(scn, scn.camera)`.  The first run of this file therefore
    # (a) crashed on `bpy.data.worlds.get(None)` AFTER saving, and (b) shipped a
    # 4.5 GB film scene lit by `save_clean`'s bare `R2_ProceduralSky` — which is
    # NOT the light `film_exposure.FILM_EXPOSURE` = -3.628 was measured under.
    # That measurement was made under build_sky INCLUDING its `SKY_AirColumn` /
    # `SKY_AirBoundary` atmosphere slab, worth 28.3005 -> 39.0106 W/m2, i.e.
    # 0.463 stops of light that R2_ProceduralSky does not have.  A film scene
    # without build_sky is a film graded for a sky it is not lit by.
    #
    # So: if the incoming scene has no world, this builds the film's own sky
    # after the rig (the rig needs to exist first — build_sky drives the world
    # off `scene.camera`), and re-saves.
    world_before = scene.world.name if scene.world else None
    if world_before is None:
        print(">> the incoming scene has NO world — build_sky will be run after "
              "the camera rig (see the note above; assembly*.blend carry no sky)")
    imgs_before = sorted(i.name for i in bpy.data.images if i.source == "FILE")
    if not a.no_rig:
        spec_mod = importlib.util.spec_from_file_location(
            "build_camera_rig", os.path.join(R2, "anim/build_camera_rig.py"))
        mod = importlib.util.module_from_spec(spec_mod)
        argv_save = sys.argv
        sys.argv = ["blender", "--", "--sheet", a.sheet, "--telemetry",
                    a.telemetry, "--spec", a.spec, "--out", a.out]
        spec_mod.loader.exec_module(mod)
        mod.main()
        sys.argv = argv_save

        world_after = scene.world.name if scene.world else None
        imgs_after = sorted(i.name for i in bpy.data.images if i.source == "FILE")
        dropped = [i for i in imgs_before if i not in imgs_after]
        if world_before is None:
            # THE FILM'S OWN LIGHT. Same call render_setup3.py makes, so the
            # film scene is lit by the sky every world render ever looked at was
            # lit by, and the sky FILM_EXPOSURE was measured under.
            import build_sky as SKY
            if scene.camera is None:
                raise SystemExit("no scene camera after the rig build — "
                                 "build_sky drives the world off it")
            sky_stats = SKY.build(scene, scene.camera)
            if scene.world is None:
                raise SystemExit("build_sky did not install a world")
            suns = [o for o in bpy.data.objects if o.type == "LIGHT"
                    and o.name.startswith("SKY_")]
            slab = [o for o in bpy.data.objects
                    if o.name in ("SKY_AirColumn", "SKY_AirBoundary")]
            if not suns or len(slab) != 2:
                raise SystemExit(
                    "build_sky left %d SKY_ lamp(s) and %d of the 2 atmosphere "
                    "slab objects. FILM_EXPOSURE was measured with both present."
                    % (len(suns), len(slab)))
            print(">> LIT by world/build_sky.py: world %r, %d SKY_ lamp(s), "
                  "atmosphere slab %s"
                  % (scene.world.name, len(suns), [o.name for o in slab]))
            print(">> build_sky stats: %s"
                  % {k: v for k, v in (sky_stats or {}).items()
                     if isinstance(v, (int, float, str, bool))})
            # R2-836.  THE CLOUD PARALLAX MUST BE BOUND TO THE CAMERA THAT
            # ACTUALLY EXISTS, AND THAT IS NOW CHECKED RATHER THAN ASSUMED.
            #
            # `build_camera_rig` DELETES every camera in the scene and builds a
            # fresh ONER. `build_sky.bind_camera()` points two SCRIPTED drivers —
            # the cloud decks' observer X and Y — at a camera object BY ID. If
            # the sky is ever built BEFORE the rig, or re-bound to a camera the
            # rig later replaces, those driver targets go to None and build_sky's
            # own docstring says what happens next: the decks "sit at world XY
            # (0,0) and behave as a skybox".
            #
            # THAT IS A GRACEFUL DEGRADATION, WHICH IS WHY IT NEEDS A GATE. No
            # error, no warning, no crash — just a different sky, and a different
            # sky is different LIGHT. It matters even for beat 1, which is an
            # interior: the showroom has a glass curtain wall and two specular
            # walls, so the sky arrives as reflection where it is not in shot.
            #
            # On THIS path the ordering is already correct — assembly*.blend
            # carries no world and no camera (verified: 0 worlds, 0 cameras), so
            # the sky cannot predate the rig. The check exists because "it has
            # always fired that way" is not a guarantee, and because the failure
            # it catches is invisible in every downstream artefact.
            _cam = scene.camera
            _w = scene.world
            _ad = getattr(getattr(_w, "node_tree", None), "animation_data", None)
            _tg = [t for fc in (_ad.drivers if _ad else [])
                   for v in fc.driver.variables for t in v.targets]
            _dangling = [t for t in _tg if t.id is None]
            _wrong = [t for t in _tg if t.id is not None and t.id is not _cam]
            if len(_tg) < 2 or _dangling or _wrong:
                raise SystemExit(
                    "REFUSING: the cloud-parallax drivers are not bound to the "
                    "live camera — %d driver target(s), %d dangling, %d pointing "
                    "at something other than %r. The decks would sit at world XY "
                    "(0,0) and render as a skybox, silently, changing the film's "
                    "light and its reflections. See R2-836."
                    % (len(_tg), len(_dangling), len(_wrong),
                       _cam.name if _cam else None))
            print(">> sky/camera bind CHECKED: %d cloud-parallax driver targets, "
                  "all live and all on %r" % (len(_tg), _cam.name))
            # the exposure/grade was applied before the rig and the rig keys a
            # DELTA from it; re-assert rather than assume nothing touched it
            got2 = FX.apply(scene)
            print(">> GRADE re-asserted after build_sky: exposure %+.3f %s %s"
                  % (got2["exposure"], got2["view_transform"], got2["look"]))
            refuse_unless_levelled(scene)   # never inside a branch -- see the docstring
            bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(a.out),
                                        compress=False)
        elif world_after != world_before:
            w = bpy.data.worlds.get(world_before)
            if w is None:
                raise SystemExit(
                    "REFUSING: the rig build replaced the world %r with %r and "
                    "the original datablock is gone. This scene would render "
                    "under a light the film's exposure was not measured in."
                    % (world_before, world_after))
            scene.world = w
            print(">> RESTORED the world: the rig build swapped %r for %r; the "
                  "assembly's own sky is back" % (world_before, world_after))
            refuse_unless_levelled(scene)   # never inside a branch -- see the docstring
            bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(a.out),
                                        compress=False)
        else:
            # R2-502.  THE PATH WITH NO SAVE ON IT.  `if world_before is None`
            # and `elif world_after != world_before` do not cover the case where
            # the incoming scene HAD a world and the rig left it alone -- and on
            # that path this function fell straight through to
            # `>> STAGE RESULT: FILM_SCENE_BUILT` having written no file at all.
            # Every assembly*.blend carries no sky, so `world_before` is None and
            # the first branch has always fired; the path has never been taken
            # and that is exactly why nobody found it.  The project's own rule is
            # to judge a stage ONLY on its STAGE RESULT line, which made an
            # unconditional success token over a conditional save a live trap.
            refuse_unless_levelled(scene)   # never inside a branch -- see the docstring
            bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(a.out),
                                        compress=False)
            print(">> world %r survived the rig build unchanged; saved on the "
                  "third path" % world_before)
        if dropped:
            raise SystemExit(
                "REFUSING: save_clean dropped %d image datablock(s) this world "
                "was using: %s. Either the world depends on an external asset "
                "(which the brief forbids and the farm cannot resolve) or the "
                "strip is too wide." % (len(dropped), dropped))
        print(">> world %r kept; %d FILE images before, %d after"
              % (scene.world.name if scene.world else None,
                 len(imgs_before), len(imgs_after)))
    else:
        os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
        refuse_unless_levelled(scene)   # never inside a branch -- see the docstring
        bpy.ops.wm.save_as_mainfile(filepath=os.path.abspath(a.out),
                                    compress=False)

    added = len(set(o.name for o in bpy.data.objects) - before_objs)
    print(">> film scene: %s -> %s  (+%d objects, %d total)"
          % (os.path.basename(src), a.out, added, len(bpy.data.objects)))
    # R2-502.  THE TOKEN MUST NOT OUTRUN THE FILE.  This line is the only thing
    # anything downstream reads, so it may not be printed on the strength of
    # having reached the end of the function -- it has to be printed on the
    # strength of a blend existing on disk that this run put there.  `t_start`
    # is taken at the top of main(); a file left over from a previous build
    # would otherwise satisfy an existence check.
    outp = os.path.abspath(a.out)
    if not os.path.exists(outp):
        print(">> STAGE RESULT: FILM_SCENE_NOT_SAVED -- reached the end of the "
              "build with no file at %s" % outp)
        return 1
    if os.path.getmtime(outp) < t_start:
        print(">> STAGE RESULT: FILM_SCENE_STALE -- %s predates this run "
              "(mtime %.0f < start %.0f); it is a previous build's output"
              % (outp, os.path.getmtime(outp), t_start))
        return 1
    print(">> saved %s  %.1f MB" % (outp, os.path.getsize(outp) / 1048576.0))
    print(">> STAGE RESULT: FILM_SCENE_BUILT")



# Imported by path, not by package: this runs inside Blender's interpreter
# with whatever cwd the caller happened to have.
import os as _os_ge, sys as _sys_ge
if _os_ge.path.dirname(_os_ge.path.abspath(__file__)) not in _sys_ge.path:
    _sys_ge.path.insert(0, _os_ge.path.dirname(_os_ge.path.abspath(__file__)))
import gate_exit                                                 # noqa: E402


if __name__ == "__main__":
    # Blender 5.2 returns 0 for a script that raised: `blender -b -P x.py`
    # prints the traceback and exits 0, MEASURED on this box. A gate that
    # crashed was indistinguishable from one that passed. guard() makes an
    # uncaught exception a status 2 and passes any real verdict through
    # unchanged. One shared helper, not N copies -- see tools/gate_exit.py.
    gate_exit.guard(main, tool="build_film_scene")
