"""IDENTITY OF EVERY INPUT A MEASUREMENT READ.  Import it, or run it.

    python3 tools/input_stamp.py --out work/tier2/inputs.json \
        --file camera world/camera_rig_path.json ...

The `world` role is filled in automatically from the ONE place that declares
it -- `render/world/assembly/r2/SHIPPING.md`, via tools/shipping_world.py --
and is overridable with `--file world <path>` when a measurement really is
against something other than the ship (a control, an A/B).

WHY THIS EXISTS
---------------
Defect #97: a placement report changed on an UNCHANGED blend, because the
telemetry and the camera path had been rebuilt underneath it, and nothing in
the report recorded either.  The report was not wrong; it was
UNATTRIBUTABLE -- there was no way to tell a real movement from a stale
instrument, and the only way to find out was to redo the work.

The screen-presence tiering reads THREE independent things, each of which is
regenerated by a different owner on a different schedule:

    the WORLD      the ship declared in SHIPPING.md          (assemble.py)
    the CAMERA     world/camera_rig_path.json                (build_camera_rig.py)
    the TELEMETRY  telemetry/telemetry.csv                   (build_telemetry.py)

plus the beat sheet (which sets the shutter ramp and the beat bounds) and the
item manifest (which sets the size each item is measured at).  A result that
does not name all five, by content, cannot be told apart from a stale one.

WHAT A STAMP IS
---------------
path, size, mtime (ISO, local), sha256 of the content, and -- for the things
that carry one -- the declared version inside the file.  sha256 is the load-
bearing field: mtime moves when a file is rewritten with identical content,
and does NOT move when a file is replaced by a copy that preserves it.  Only
the hash answers "is this the same bytes the last run read".

Hashing a 4.2 GB blend costs about 20 s of one core.  That is the whole price
of never again having to ask whether a number moved because the world moved.
"""
import os, sys, json, time, hashlib, argparse

R2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if os.path.dirname(os.path.abspath(__file__)) not in sys.path:
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from shipping_world import declared_shipping_path        # noqa: E402


# The five inputs the screen-presence tiering actually reads, so a caller
# cannot forget one.  Anything else is passed with --file.
#
# THE WORLD IS NOT A LITERAL HERE ANY MORE, AND THAT IS THE POINT.  This dict
# said `assembly6.blend` from the day it was written, through the `assembly7`
# promotion (2026-08-03 04:45) and the `assembly8` rebuild, because a default
# argument does not look like a decision and so nobody owned it.  That is
# R2-071's shape exactly -- a second copy of a fact, going stale where nothing
# reads it out loud -- and a stamping tool carrying it is the worst place for
# it: the whole purpose of a stamp is to say WHICH world a number was measured
# against, and this one would have confidently named the wrong file.
#
# `render/world/assembly/r2/SHIPPING.md` is the single declaration.  It is
# parsed once, in tools/shipping_world.py, and RAISES rather than defaulting.
def default_inputs():
    return {
        "world": declared_shipping_path(),
        "camera_path": "world/camera_rig_path.json",
        "telemetry": "telemetry/telemetry.csv",
        "beat_sheet": "docs/beat_sheet.json",
        "item_manifest": "docs/item_manifest.json",
        "world_contract": "world/world_contract.py",
    }


def sha256(path, chunk=1 << 22):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while True:
            b = fh.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def declared_version(path):
    """The version a file states about ITSELF, where it states one.

    A hash proves identity but says nothing a human can argue with.  The
    contract version is the number the rest of the project quotes at each
    other, so it is worth carrying next to the hash -- with the caveat that
    it is prose: assembly5 and assembly6 disagree by 3.19 m of wall and
    BOTH report contract 1.2.0.  The version is a label; the hash is the fact.
    """
    try:
        if path.endswith("world_contract.py"):
            for line in open(path, encoding="utf-8", errors="replace"):
                if line.startswith("__version__"):
                    return line.split("=", 1)[1].strip().strip('"\'')
        if path.endswith(".blend"):
            side = path[:-6] + "_build.json"
            if os.path.exists(side):
                return json.load(open(side)).get("contract")
        if path.endswith("camera_rig_path.json"):
            d = json.load(open(path))
            return "frames=%d" % d.get("frames", len(d.get("path", [])))
        if path.endswith("beat_sheet.json"):
            d = json.load(open(path))
            return "frames=%s beats=%d" % (d.get("total_frames"), len(d.get("beats", [])))
    except Exception as exc:                                   # noqa: BLE001
        return "unreadable: %r" % (exc,)
    return None


def stamp_one(role, path):
    p = os.path.abspath(path if os.path.isabs(path) else os.path.join(R2, path))
    if not os.path.exists(p):
        return {"role": role, "path": p, "MISSING": True}
    st = os.stat(p)
    return {
        "role": role,
        "path": p,
        "bytes": st.st_size,
        "mtime": time.strftime("%Y-%m-%dT%H:%M:%S", time.localtime(st.st_mtime)),
        "mtime_epoch": int(st.st_mtime),
        "sha256": sha256(p),
        "declares": declared_version(p),
    }


def stamp(extra=None, defaults=True):
    items = default_inputs() if defaults else {}
    items.update(extra or {})
    return {
        "stamped_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "host": os.uname().nodename,
        "WHY": "Defect #97: a report changed on an unchanged blend because the "
               "telemetry and camera were rebuilt underneath it and nothing "
               "recorded it. sha256 is the load-bearing field; mtime and the "
               "declared version are context. A result that cannot be told "
               "apart from a stale one is not a result.",
        "inputs": [stamp_one(k, v) for k, v in items.items()],
    }


def diff(a, b):
    """Which stamped inputs differ between two stamps. Returns (changed, same)."""
    da = {i["role"]: i for i in a["inputs"]}
    db = {i["role"]: i for i in b["inputs"]}
    changed, same = [], []
    for r in sorted(set(da) | set(db)):
        x, y = da.get(r), db.get(r)
        if x is None or y is None or x.get("sha256") != y.get("sha256"):
            changed.append(r)
        else:
            same.append(r)
    return changed, same


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--file", nargs=2, action="append", metavar=("ROLE", "PATH"),
                    default=[], help="extra input to stamp")
    ap.add_argument("--no-defaults", action="store_true")
    ap.add_argument("--against", default="", help="an earlier stamp json to diff against")
    a = ap.parse_args()
    s = stamp(dict(a.file), defaults=not a.no_defaults)
    if a.against and os.path.exists(a.against):
        ch, sm = diff(json.load(open(a.against)), s)
        s["diff_against"] = {"file": os.path.abspath(a.against),
                             "CHANGED": ch, "identical": sm}
        print("[STAMP] vs %s  CHANGED=%s  identical=%s" % (a.against, ch, sm))
    os.makedirs(os.path.dirname(os.path.abspath(a.out)) or ".", exist_ok=True)
    json.dump(s, open(a.out, "w"), indent=1)
    for i in s["inputs"]:
        print("[STAMP] %-15s %s  %s  %s" % (i["role"], i.get("mtime", "MISSING"),
                                            (i.get("sha256") or "")[:16],
                                            i.get("declares") or ""))
    print("[STAMP] wrote " + a.out)


if __name__ == "__main__":
    main()
