#!/bin/bash
# RE-DERIVE THE HERO/MID/BULK TIERING AND THE AGENT COUNTS, END TO END.
#
#   bash tools/retier.sh [ASSEMBLY_BLEND]
#
# There is no other route. Run this, not the individual tools, so that the
# input stamp and the measurement can never disagree about what was read.
#
# WHAT IT READS, AND WHY ALL OF IT IS STAMPED
# -------------------------------------------
# The tiering is a function of THREE things that are regenerated by three
# different owners on three different schedules -- the WORLD, the CAMERA and
# the TELEMETRY -- plus the beat sheet (shutter ramp and beat bounds) and the
# item manifest (the size each item is measured at). Defect #97 was a
# placement report that changed on an UNCHANGED blend because two of those had
# been rebuilt underneath it and nothing recorded which. Step 0 below writes
# the sha256 of all of them next to the answer.
#
# TWO THINGS THAT ARE NOT OBVIOUS AND COST A DAY EACH IF REDISCOVERED
# ------------------------------------------------------------------
# 1. --cap 2000000, NOT the 250000 default. Exactly one object in this world
#    exceeds the default cap -- TER_Ground, at ~589,000 occupied cells -- and
#    it is the sole host of 8 manifest items and a host of 15. At the default
#    cap its point set is a 42 % RANDOM SUBSAMPLE drawn from a seeded RNG whose
#    state depends on how many objects were capped before it, so the ground
#    cells nearest the lens -- which is what decides those 15 items' tier -- are
#    a draw rather than a fact.
#    HONESTY ABOUT WHAT THIS DID AND DID NOT CAUSE: when assembly2 and assembly6
#    disagreed about the nearest ground point to the camera (1.58 m vs 7.45 m),
#    the subsample was the obvious suspect and was WRONG. Re-dumping both worlds
#    uncapped reproduces 1.58 m and 7.45 m exactly: the ground really did move,
#    and the cap was innocent. Raise it anyway -- a tiering that could have been
#    a lottery and happened not to be is not a standard worth keeping -- but do
#    not repeat the inference. The cost is 340 k extra points, about 13 %.
# 2. --uniform-shutter IS THE SHIPPING MODE. Since R2-037 the rig keys a flat
#    180-degree shutter for the whole take; without the flag screen_presence.py
#    reproduces the old ramped shutter, which left beat 3's static geometry
#    6.5x too crisp. Omitting the flag is only useful as the other half of a
#    diff.
#
# WHICH BLEND. render/world/assembly/r2/SHIPPING.md is the authority.
# assembly5.blend MUST NOT BE USED: its Beat-4 north wall stands 3.19 m out of
# place because it was built 71 minutes before the telemetry fix it is believed
# to be built against, and its module summaries are BIT-IDENTICAL to
# assembly6's, so no summary-level check can tell them apart.
set -e
cd "$(dirname "$0")/.." || exit 1
BLEND=${1:-render/world/assembly/r2/assembly6.blend}
OUT=work/retier
mkdir -p $OUT

case "$BLEND" in
  *assembly5.blend) echo "REFUSING: assembly5 is SUPERSEDED, see SHIPPING.md"; exit 2;;
esac

# 0. identity of every input, BEFORE anything reads them
python3 tools/input_stamp.py --out $OUT/inputs.json --file world "$BLEND"

# 1. world positions: a 1 m voxel surface sample, uncapped
blender -b --factory-startup -P tools/dump_world_points.py -- \
  --blend "$BLEND" --out $OUT/world_points.npz --cell 1.0 --cap 2000000

# 2. screen presence against the real camera
python3 tools/screen_presence.py --points $OUT/world_points.npz \
  --path world/camera_rig_path.json --sheet docs/beat_sheet.json \
  --uniform-shutter --out $OUT/sp_objects.json --npz $OUT/sp_points.npz

# 3. per-item table + the re-tier
python3 tools/item_presence.py --npz $OUT/sp_points.npz \
  --sheet docs/beat_sheet.json --objects $OUT/sp_objects.json \
  --out $OUT/item_presence.json --tiers $OUT/tiers_raw.json

# 4. vantage regimes -> the FRAME-peep count
python3 tools/frame_peeps.py --path world/camera_rig_path.json \
  --sheet docs/beat_sheet.json --out $OUT/frame_peeps.json

# 5. the campaign plan: tier counts, agent counts, stamped
python3 tools/agents_per_round.py --items $OUT/item_presence.json \
  --peeps $OUT/frame_peeps.json --stamp $OUT/inputs.json \
  --against docs/proposed_tiers.json --out $OUT/proposed_tiers.json

echo "=== $OUT/proposed_tiers.json ==="
python3 -c "import json;d=json.load(open('$OUT/proposed_tiers.json'));print(d['tier_counts']);print({k:(v.get('agents') if isinstance(v,dict) else v) for k,v in d['agents_per_round'].items()})"
